"""Shared models and model factory for the Excel-chat agent and pipeline.

This module contains the Pydantic models (PlanStep, QueryPlan,
ExecutionResult, FriendlyResponse), the _flatten_value helper used by
ExecutionResult's validator, and the OpenRouter model factory
(PRIMARY_MODEL, FALLBACK_MODEL, build_openrouter_model).

Both agent.py and pipeline.py import from here — no circular dependencies.
"""

from __future__ import annotations

import json
import os
from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator
from pydantic_ai.models.openai import OpenAIChatModel
from pydantic_ai.providers.openai import OpenAIProvider


# ============================================================================
# Structured Output Models
# ============================================================================

class PlanStep(BaseModel):
    """A single step in the execution plan."""
    action: Literal[
        "retrieve", "compute",
        "add", "subtract", "multiply", "divide", "return_percentage",
        "sqrt", "power", "log", "exp", "abs", "negate",
        "max", "min", "average", "median", "stdev",
        "yoy_growth", "cagr", "ratio", "percentage_change", "difference",
    ] = Field(
        description=(
            "The action to perform. "
            "'retrieve' fetches value(s) from the DataFrame — pass one or more years. "
            "'compute' runs arbitrary Python code in a secure sandbox for complex calculations. "
            "Named operations (add, subtract, multiply, divide, return_percentage, sqrt, power, "
            "log, exp, abs, negate, max, min, average, median, stdev, yoy_growth, cagr, ratio, "
            "percentage_change, difference) apply the corresponding math function to prior step results."
        )
    )
    args: list[str] = Field(
        description=(
            "For 'retrieve': ['FieldName', 'Year1', 'Year2', ...] to search all sheets, "
            "or ['SheetName', 'FieldName', 'Year1', 'Year2', ...] to search a specific sheet. "
            "Pass one year for a single value or multiple years for a batch. "
            "For 'compute': a natural-language description of the calculation. "
            "For named operations: references to prior steps (e.g. ['step1', 'step2']) "
            "or literal numbers (e.g. ['step1', '100']). "
            "Unary ops (sqrt, abs, negate, exp): one arg. "
            "Binary ops (subtract, divide, return_percentage, power, log, yoy_growth, ratio, "
            "percentage_change, difference): two args. "
            "Ternary ops (cagr): three args [end_value, start_value, num_years]. "
            "N-ary ops (add, multiply, max, min, average, median, stdev): two or more args."
        )
    )
    description: str = Field(
        default="",
        description=(
            "Short present-continuous action label for the UI plan card, "
            "e.g. 'Retrieving social security benefits 2017-2021' or 'Calculating CAGR'."
        ),
    )


class QueryPlan(BaseModel):
    """Structured plan generated by the planner agent."""
    task_type: Literal[
        "retrieve_numbers", "perform_calculations", "give_advice", "other"
    ] = Field(description="The type of task the user is asking for.")
    plan: dict[str, PlanStep] | None = Field(
        default=None,
        description="Numbered steps for 'perform_calculations' tasks.",
    )
    items: list[str] | None = Field(
        default=None,
        description="List of 'FieldName, Year' strings for 'retrieve_numbers' tasks.",
    )
    description: str | None = Field(
        default=None,
        description="Description of advice needed for 'give_advice' tasks.",
    )

    @field_validator("plan", mode="before")
    @classmethod
    def _parse_plan(cls, v):
        if isinstance(v, list):
            converted = {}
            for i, item in enumerate(v, 1):
                if isinstance(item, dict):
                    if "step" in item and isinstance(item["step"], dict):
                        converted[f"step{i}"] = item["step"]
                    else:
                        converted[f"step{i}"] = item
                else:
                    converted[f"step{i}"] = item
            return converted
        if isinstance(v, str):
            try:
                parsed = json.loads(v)
                if isinstance(parsed, dict):
                    return parsed
                if isinstance(parsed, list):
                    return cls._parse_plan(parsed)
            except (json.JSONDecodeError, TypeError):
                pass
        return v

    @field_validator("items", mode="before")
    @classmethod
    def _parse_items(cls, v):
        if isinstance(v, str):
            try:
                parsed = json.loads(v)
                if isinstance(parsed, list):
                    return parsed
            except (json.JSONDecodeError, TypeError):
                pass
        return v


def _flatten_value(v: Any) -> Any:
    """Flatten dict/list values to readable strings so the frontend doesn't show [object Object]."""
    if isinstance(v, dict):
        if "value" in v and len(v) == 1:
            return v["value"]
        return json.dumps(v, default=str)
    if isinstance(v, list):
        return json.dumps(v, default=str)
    return v


class ExecutionResult(BaseModel):
    """Result of executing a query plan."""
    step_results: dict[str, Any] = Field(
        default_factory=dict,
        description="Results from each executed step.",
    )
    final_answer: Any = Field(
        description="The final computed or retrieved answer.",
    )
    explanation: str = Field(
        default="",
        description="Brief explanation of how the answer was derived.",
    )
    friendly_response: str = Field(
        default="",
        description="A clear, natural language response to the user's question. "
        "Include specific numerical values with proper formatting (currency, percentages). "
        "Briefly explain how the answer was derived. Use a friendly, professional tone.",
    )

    @field_validator("final_answer", "step_results", mode="before")
    @classmethod
    def _flatten_nested_objects(cls, v):
        if isinstance(v, dict):
            return {k: _flatten_value(val) for k, val in v.items()}
        return _flatten_value(v)


class FriendlyResponse(BaseModel):
    """User-friendly natural language response."""
    response: str = Field(description="The conversational response to the user.")


# ============================================================================
# Model Factory
# ============================================================================

PRIMARY_MODEL = os.environ.get("MODEL_ID", "deepseek/deepseek-v4-flash")
FALLBACK_MODEL = os.environ.get("FALLBACK_MODEL_ID", "openai/gpt-oss-120b:nitro")


def build_openrouter_model(model_name: str | None = None) -> OpenAIChatModel:
    """Create an OpenAIChatModel configured for OpenRouter.

    If *model_name* is provided, use it; otherwise fall back to the primary
    model from the ``MODEL_ID`` env var.
    """
    return OpenAIChatModel(
        model_name=model_name or PRIMARY_MODEL,
        provider=OpenAIProvider(
            base_url=os.environ.get("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1"),
            api_key=os.environ.get("OPENROUTER_API_KEY"),
        ),
    )
