from __future__ import annotations

import json
import os
import time
from contextlib import contextmanager
from typing import Any, Callable, Literal

import pandas as pd
from pydantic import BaseModel, Field, field_validator
from pydantic_ai import Agent, Tool
from pydantic_ai.models.openai import OpenAIModel

from llama_index.core.prompts import PromptTemplate

from sheet_metadata import SheetMeta
from guardrails import GUARDRAIL_SYSTEM_PROMPT, inject_disclaimer
from tools import (
    PipelineDeps,
    NAMED_OPERATIONS,
    retrieve,
    extract_val,
    retrieve_batch,
    execute_python_code,
    analyze_sheet,
    find_missing_data,
    discover_column_types,
    get_sheet_shape,
    group_summary_stats,
    create_pivot_table,
    crosstab_analysis,
    drop_missing_columns,
    convert_to_numerical,
    correlation_analysis,
    get_sheet_head,
    get_sheet_info,
    value_counts_analysis,
    deduplicate_rows,
    get_sheet_dtypes,
    _prepare_retrieve_tool,
    _prepare_extract_val_tool,
    _prepare_retrieve_batch_tool,
)


# ============================================================================
# Timing Instrumentation (Optimization 6)
# ============================================================================

@contextmanager
def timed(stage: str, timings: dict[str, float]):
    """Record elapsed wall-clock time for ``stage`` into ``timings``.

    Usage:
        timings: dict[str, float] = {}
        with timed("planner", timings):
            ...
        # timings["planner"] now holds the elapsed seconds.

    Failures inside the ``with`` block propagate normally; the elapsed time is
    recorded either way so a slow failed stage is still visible in logs.
    """
    start = time.perf_counter()
    try:
        yield
    finally:
        elapsed = time.perf_counter() - start
        timings[stage] = timings.get(stage, 0.0) + elapsed
        print(f"[{stage}] {elapsed:.2f}s")


# ============================================================================
# Structured Output Models
# ============================================================================

class PlanStep(BaseModel):
    """A single step in the execution plan."""
    action: Literal[
        "retrieve", "retrieve_batch", "compute",
        "add", "subtract", "multiply", "divide", "return_percentage",
        "sqrt", "power", "log", "exp", "abs", "negate",
        "max", "min", "average", "median", "stdev",
        "yoy_growth", "cagr", "ratio", "percentage_change", "difference",
    ] = Field(
        description=(
            "The action to perform. "
            "'retrieve' fetches a single value from the DataFrame. "
            "'retrieve_batch' fetches multiple year values for one field in ONE call "
            "(preferred when you need 2+ years for the same field — saves LLM round-trips). "
            "'compute' runs arbitrary Python code in a secure sandbox for complex calculations. "
            "Named operations (add, subtract, multiply, divide, return_percentage, sqrt, power, "
            "log, exp, abs, negate, max, min, average, median, stdev, yoy_growth, cagr, ratio, "
            "percentage_change, difference) apply the corresponding math function to prior step results."
        )
    )
    args: list[str] = Field(
        description=(
            "For 'retrieve': ['FieldName', 'Year'] to search all sheets, "
            "or ['SheetName', 'FieldName', 'Year'] to search a specific sheet. "
            "For 'retrieve_batch': ['FieldName', 'Year1', 'Year2', ...] for cross-sheet, "
            "or ['SheetName', 'FieldName', 'Year1', 'Year2', ...] for a specific sheet. "
            "For 'compute': a natural-language description of the calculation. "
            "For named operations: references to prior steps (e.g. ['step1', 'step2']) "
            "or literal numbers (e.g. ['step1', '100']). "
            "Unary ops (sqrt, abs, negate, exp): one arg. "
            "Binary ops (subtract, divide, return_percentage, power, log, yoy_growth, ratio, "
            "percentage_change, difference): two args. "
            "Ternary ops (cagr): three args [end_value, start_value, num_years]. "
            "N-ary ops (add, multiply, max, min, average, median, stdev): two or more args."
        )
    )


class QueryPlan(BaseModel):
    """Structured plan generated by the planner agent."""
    task_type: Literal[
        "retrieve_numbers", "perform_calculations", "give_advice", "other"
    ] = Field(description="The type of task the user is asking for.")
    plan: dict[str, PlanStep] | None = Field(
        default=None,
        description="Numbered steps for 'perform_calculations' tasks.",
    )
    items: list[str] | None = Field(
        default=None,
        description="List of 'FieldName, Year' strings for 'retrieve_numbers' tasks.",
    )
    description: str | None = Field(
        default=None,
        description="Description of advice needed for 'give_advice' tasks.",
    )

    @field_validator("plan", mode="before")
    @classmethod
    def _parse_plan(cls, v):
        if isinstance(v, list):
            converted = {}
            for i, item in enumerate(v, 1):
                if isinstance(item, dict):
                    if "step" in item and isinstance(item["step"], dict):
                        converted[f"step{i}"] = item["step"]
                    else:
                        converted[f"step{i}"] = item
                else:
                    converted[f"step{i}"] = item
            return converted
        if isinstance(v, str):
            try:
                parsed = json.loads(v)
                if isinstance(parsed, dict):
                    return parsed
                if isinstance(parsed, list):
                    return cls._parse_plan(parsed)
            except (json.JSONDecodeError, TypeError):
                pass
        return v

    @field_validator("items", mode="before")
    @classmethod
    def _parse_items(cls, v):
        if isinstance(v, str):
            try:
                parsed = json.loads(v)
                if isinstance(parsed, list):
                    return parsed
            except (json.JSONDecodeError, TypeError):
                pass
        return v


def _flatten_value(v: Any) -> Any:
    """Flatten dict/list values to readable strings so the frontend doesn't show [object Object]."""
    if isinstance(v, dict):
        if "value" in v and len(v) == 1:
            return v["value"]
        return json.dumps(v, default=str)
    if isinstance(v, list):
        return json.dumps(v, default=str)
    return v


class ExecutionResult(BaseModel):
    """Result of executing a query plan."""
    step_results: dict[str, Any] = Field(
        default_factory=dict,
        description="Results from each executed step.",
    )
    final_answer: Any = Field(
        description="The final computed or retrieved answer.",
    )
    explanation: str = Field(
        default="",
        description="Brief explanation of how the answer was derived.",
    )
    friendly_response: str = Field(
        default="",
        description="A clear, natural language response to the user's question. "
        "Include specific numerical values with proper formatting (currency, percentages). "
        "Briefly explain how the answer was derived. Use a friendly, professional tone.",
    )

    @field_validator("final_answer", "step_results", mode="before")
    @classmethod
    def _flatten_nested_objects(cls, v):
        if isinstance(v, dict):
            return {k: _flatten_value(val) for k, val in v.items()}
        return _flatten_value(v)


class FriendlyResponse(BaseModel):
    """User-friendly natural language response."""
    response: str = Field(description="The conversational response to the user.")


# ============================================================================
# Model Factory
# ============================================================================

PRIMARY_MODEL = os.environ.get("MODEL_ID", "openai/gpt-oss-120b:nitro")
FALLBACK_MODEL = os.environ.get("FALLBACK_MODEL_ID", "deepseek/deepseek-v4-pro")


def build_openrouter_model(model_name: str | None = None) -> OpenAIModel:
    """Create an OpenAIModel configured for OpenRouter.

    If *model_name* is provided, use it; otherwise fall back to the primary
    model from the ``MODEL_ID`` env var.
    """
    return OpenAIModel(
        model_name=model_name or PRIMARY_MODEL,
        base_url=os.environ.get("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1"),
        api_key=os.environ.get("OPENROUTER_API_KEY"),
    )


# ============================================================================
# Agent Builders
# ============================================================================

def build_planner_agent(sheets: dict[str, pd.DataFrame], sheet_metas: list[SheetMeta], model_name: str | None = None) -> Agent[None, QueryPlan]:
    """Agent that generates a structured QueryPlan from a user question."""
    model = build_openrouter_model(model_name)

    # Build multi-sheet context
    sheet_context_parts = []
    all_fields = set()
    all_years = set()
    for meta in sheet_metas:
        all_fields.update(meta.fields)
        all_years.update(meta.years)
        group_note = f" (schema group: {meta.schema_group})" if meta.schema_group and meta.schema_group != "unique" else ""
        desc_note = f"\n      Description: {meta.combined_description}" if meta.combined_description != "No description available." else ""
        sheet_context_parts.append(
            f"  - Sheet '{meta.sheet_name}' (file: {meta.file_name}){group_note}\n"
            f"      Fields: {', '.join(meta.fields[:20])}\n"
            f"      Years: {', '.join(meta.years)}{desc_note}"
        )
    sheet_context = "\n".join(sheet_context_parts)
    fields_str = ", ".join(sorted(all_fields))
    years_str = ", ".join(sorted(all_years))

    # Identify schema groups for cross-sheet note
    groups = {}
    for meta in sheet_metas:
        if meta.schema_group and meta.schema_group != "unique":
            groups.setdefault(meta.schema_group, []).append(meta.sheet_name)
    cross_sheet_note = ""
    if groups:
        group_descs = [f"  - {', '.join(sheets_list)}" for sheets_list in groups.values()]
        cross_sheet_note = f"\n    Cross-sheet calculations are possible for sheets with the same schema group:\n{chr(10).join(group_descs)}\n    When retrieving from a schema group, omit the sheet name to search all sheets in that group."

    instructions = f"""You are a financial data analysis planner.

    Available sheets and their data:
{sheet_context}

    All available fields across sheets: {fields_str}
    All available years across sheets: {years_str}
{cross_sheet_note}

    Task types:
    - retrieve_numbers: Simple lookups (e.g., "What was revenue in 2022?")
    - perform_calculations: Any math or comparison (e.g., "What's the profit margin?", "Compare YoY growth")
    - give_advice: Recommendations or analysis
    - other: Everything else

    For retrieve_numbers: return items like ["Revenue, 2022"] or ["SheetName, Revenue, 2022"] for sheet-specific retrieval.
    For perform_calculations: return a plan using these step types:

    1. retrieve — fetch a single value: args = ["FieldName", "Year"] (searches all sheets) or ["SheetName", "FieldName", "Year"] (specific sheet)
    2. retrieve_batch — fetch multiple year values for ONE field in a single step (PREFERRED when 2+ years needed for the same field — saves executor LLM round-trips):
       args = ["FieldName", "Year1", "Year2", ...] for cross-sheet, or
              ["SheetName", "FieldName", "Year1", "Year2", ...] for a specific sheet
       Example: step1: retrieve_batch ["Capital expenditure", "2018", "2019", "2020", "2021", "2022"]
    3. Named math operations — apply to prior step results or literal numbers:
       - Unary (1 arg): sqrt, abs, negate, exp
       - Binary (2 args): subtract, divide, return_percentage, power, log, yoy_growth, ratio, percentage_change, difference
       - Ternary (3 args): cagr [end_value, start_value, num_years]
       - N-ary (2+ args): add, multiply, max, min, average, median, stdev
       Args can be step references (e.g. "step1") or literal numbers (e.g. "100").
    3. compute — for complex multi-step calculations that can't be expressed with named ops,
       provide a natural-language description of the calculation as args[0].
       The executor will translate this into Python code and run it in a sandbox.

    Prefer named operations for simple math. Use compute for complex formulas,
    multi-step calculations, or when you need math module functions not covered above.

    When a query involves data from multiple sheets (especially in the same schema group),
    use retrieve with specific sheet names to get values from each sheet, then apply
    named operations or compute to combine them.

    Examples:

    [Simple percentage - single sheet]
    step1: retrieve ["Wages and salaries", "2022"]
    step2: retrieve ["Expense", "2022"]
    step3: return_percentage ["step1", "step2"]

    [YoY growth]
    step1: retrieve ["Revenue", "2023"]
    step2: retrieve ["Revenue", "2022"]
    step3: yoy_growth ["step1", "step2"]

    [Cross-sheet comparison - same schema group]
    step1: retrieve ["Sheet1", "Revenue", "2022"]
    step2: retrieve ["Sheet2", "Revenue", "2022"]
    step3: subtract ["step1", "step2"]

    [Cross-sheet average across all sheets]
    step1: retrieve ["Revenue", "2022"]  (returns values from all matching sheets)
    step2: compute ["Calculate the average of all Revenue 2022 values retrieved in step1"]

    [CAGR over 5 years]
    step1: retrieve ["Revenue", "2023"]
    step2: retrieve ["Revenue", "2018"]
    step3: cagr ["step1", "step2", "5"]

    [Multi-year batch (preferred over N retrievals)]
    step1: retrieve_batch ["Capital expenditure", "2018", "2019", "2020", "2021", "2022"]
    step2: compute ["Find the year with the lowest capital expenditure among step1"]

    [Complex calculation via compute]
    step1: retrieve ["Revenue", "2023"]
    step2: retrieve ["Revenue", "2021"]
    step3: retrieve ["Expenses", "2023"]
    step4: compute ["Calculate the compound annual growth rate of Revenue from 2021 to 2023, then multiply by the 2023 profit margin (Revenue - Expenses) / Revenue"]

    Always use exact field names and years from the available lists.
    {GUARDRAIL_SYSTEM_PROMPT}
    """

    return Agent(
        model,
        result_type=QueryPlan,
        system_prompt=instructions,
        model_settings={"temperature": 0.1},
        result_retries=2,
    )


def build_executor_agent(sheets: dict[str, pd.DataFrame], sheet_metas: list[SheetMeta], model_name: str | None = None) -> Agent[PipelineDeps, ExecutionResult]:
    """Agent that executes a plan using tools, with structured output."""
    model = build_openrouter_model(model_name)

    retrieve_t = Tool(retrieve, prepare=_prepare_retrieve_tool)
    extract_t = Tool(extract_val, prepare=_prepare_extract_val_tool)
    retrieve_batch_t = Tool(retrieve_batch, prepare=_prepare_retrieve_batch_tool)

    sheet_names = list(sheets.keys())
    system_prompt = f"""You are a financial data execution engine.

    You have access to {len(sheets)} sheet(s): {', '.join(sheet_names)}

    You have three tools:
    1. retrieve / extract_val — fetch a SINGLE value for a (field, year) pair
       - If a sheet name is provided, searches only that sheet.
       - If no sheet name is provided, searches all sheets and returns all matching values.
    2. retrieve_batch — fetch MULTIPLE year values for ONE field in a single tool call.
       PREFER THIS TOOL when you need 2+ years for the same field — each call to
       retrieve is a separate LLM round-trip, but retrieve_batch collapses them
       into one. For example, instead of:
           retrieve("Capital", "2018"); retrieve("Capital", "2019"); retrieve("Capital", "2020");
       do:
           retrieve_batch("Capital", ["2018", "2019", "2020"])
       Returns a JSON object like {{"2018": 1500.0, "2019": 1200.0}} for single-sheet
       mode, or {{"2018": {{"Sheet1": 1500.0, "Sheet2": 1300.0}}}} for cross-sheet mode.
    3. execute_python_code — run Python code in a secure sandbox to perform ANY calculation

    You also have EDA (exploratory data analysis) tools for DataFrame-level inspection:
    4. analyze_sheet(sheet_name) — comprehensive EDA: dimensions, describe(), duplicates, per-column stats
    5. find_missing_data(sheet_name) — missing data report (counts and percentages per column)
    6. discover_column_types(sheet_name) — classify columns as categorical/discrete/continuous
    7. get_sheet_shape(sheet_name) — return row x column dimensions
    8. group_summary_stats(sheet_name, group_col, value_col) — groupby with count/sum/mean/median/std/min/max
    9. create_pivot_table(sheet_name, index, columns, values) — pivot table with mean aggregation
    10. crosstab_analysis(sheet_name, col1, col2, aggfunc) — cross-tabulation (aggfunc: mean/median/count/std)
    11. drop_missing_columns(sheet_name, threshold) — drop columns with missing data above threshold fraction
    12. convert_to_numerical(sheet_name, columns) — convert categorical columns to numerical, fill NaN with mean
    13. correlation_analysis(sheet_name, columns) — full correlation matrix for numerical columns
    14. get_sheet_head(sheet_name, n) — first N rows (like df.head(n))
    15. get_sheet_info(sheet_name) — dtypes, non-null counts, memory usage (like df.info())
    16. value_counts_analysis(sheet_name, column, normalize) — value counts for a column
    17. deduplicate_rows(sheet_name, subset) — find and report duplicate rows
    18. get_sheet_dtypes(sheet_name) — dtype of each column

    Use EDA tools when the user asks about data quality, distributions, correlations,
    missing values, column types, or wants a summary/overview of the data.
    Use retrieve/retrieve_batch + execute_python_code for specific value lookups and calculations.

    The sandbox supports:
    - Basic Python syntax and operators (+, -, *, /, **, //, %)
    - math module (math.sqrt, math.pow, math.log, math.exp, math.ceil, math.floor, etc.)
    - Common builtins (abs, round, min, max, sum, len, sorted)
    - NumPy functions: np_mean, np_std, np_median, np_var, np_min, np_max, np_sum,
      np_percentile, np_diff, np_cumsum, np_cumprod, np_arange, np_linspace,
      np_sqrt, np_exp, np_log, np_abs, np_round, np_dot, np_corrcoef,
      np_argmax, np_argmin
      (all accept Python lists or scalars and return Python floats/lists)
    - Pandas functions: pd_series, pd_rolling_mean, pd_rolling_std,
      pd_describe (returns dict with count/mean/std/min/25%/50%/75%/max),
      pd_deduplicate (returns unique values), pd_value_counts (returns frequency dict),
      np_histogram (returns counts and bin_edges)
      (all accept Python lists and return JSON-serializable types)

    Execution flow:
    1. Call retrieve_batch (preferred when you need multiple years for one field)
       or retrieve (for single values) to get all needed values from the plan
    2. For named operations (add, subtract, multiply, divide, return_percentage, sqrt, power,
       log, exp, abs, negate, max, min, average, median, stdev, yoy_growth, cagr, ratio,
       percentage_change, difference): either compute directly in Python or use execute_python_code
    3. For compute steps: call execute_python_code with Python code that performs the full
       calculation using the retrieved values as literal numbers
    4. For EDA / exploratory analysis questions, use the EDA tools (analyze_sheet,
       find_missing_data, discover_column_types, get_sheet_shape, group_summary_stats,
       create_pivot_table, crosstab_analysis, drop_missing_columns, convert_to_numerical,
       correlation_analysis) to inspect the DataFrame directly.
    5. Return the final answer as structured data.

    ### CRITICAL — step_results MUST be populated:
    The `step_results` field in your output MUST contain an entry for EVERY step in the plan,
    including pre-populated steps. For each step key (e.g. "step1", "step2"), set its value
    to the result of that step. For retrieve/retrieve_batch steps, use the retrieved value(s).
    For named operations and compute steps, use the computed result.
    Example: if the plan has step1 (retrieve_batch), step2 (retrieve_batch), step3 (compute),
    then step_results should be: {{"step1": {{...}}, "step2": {{...}}, "step3": <computed_value>}}.
    Do NOT leave step_results as an empty dict {{}}.

    ### CRITICAL — friendly_response MUST use actual field names:
    When writing the `friendly_response` field, ALWAYS refer to the actual field names from
    the plan — never use generic phrases like "the first series" or "the second value".
    For example, instead of "The first benefit series grew at 25.4%", write
    "Social security benefits grew at a CAGR of 25.4%".
    The field names are provided in the execution prompt alongside each step.

    When retrieve returns multiple values (from searching all sheets), parse them carefully.
    The format is "SheetName: value; SheetName2: value2".

    When writing Python code for execute_python_code:
    - Use the retrieved numeric values directly as literals in the code
    - Use a `return` statement to return the final result
    - Example: code = 'revenue = 1500000\\nexpenses = 800000\\nmargin = (revenue - expenses) / revenue * 100\\nreturn margin'

    If a retrieval fails, note it and continue with what you can.
    {GUARDRAIL_SYSTEM_PROMPT}
    """

    return Agent(
        model,
        deps_type=PipelineDeps,
        result_type=ExecutionResult,
        system_prompt=system_prompt,
        tools=[
            retrieve_t,
            extract_t,
            retrieve_batch_t,
            execute_python_code,
            analyze_sheet,
            find_missing_data,
            discover_column_types,
            get_sheet_shape,
            group_summary_stats,
            create_pivot_table,
            crosstab_analysis,
            drop_missing_columns,
            convert_to_numerical,
            correlation_analysis,
            get_sheet_head,
            get_sheet_info,
            value_counts_analysis,
            deduplicate_rows,
            get_sheet_dtypes,
        ],
        model_settings={"temperature": 0.1},
        result_retries=2,
    )


def build_responder_agent(model_name: str | None = None) -> Agent[None, str]:
    """Agent that generates a friendly natural language response."""
    model = build_openrouter_model(model_name)

    return Agent(
        model,
        result_type=str,
        system_prompt=f"""You are a helpful financial assistant.

        Given a user's question and the calculated results, provide a clear, conversational
        response that directly answers the question. Include specific numerical values
        with proper formatting (currency, percentages). Briefly explain how the answer
        was derived. Use a friendly, professional tone.
        {GUARDRAIL_SYSTEM_PROMPT}
        """,
        model_settings={"temperature": 0.3},
    )


def _is_empty_response_error(exc: Exception) -> bool:
    """Check whether *exc* is an empty-model-response error from pydantic-ai."""
    msg = str(exc).lower()
    return "empty model response" in msg or "received empty" in msg


async def _run_with_fallback(
    build_agent: Callable[..., Agent],
    prompt: str,
    *args,
    deps: Any = None,
    **kwargs,
) -> Any:
    """Run an agent, retrying with the fallback model on empty-response errors.

    *build_agent* is called with *args* and **kwargs to create the primary
    agent. If the primary agent's ``run`` raises an empty-response error, the
    same builder is called with ``model_name=FALLBACK_MODEL`` and retried.
    """
    agent = build_agent(*args, **kwargs)
    try:
        if deps is not None:
            return await agent.run(prompt, deps=deps)
        return await agent.run(prompt)
    except Exception as exc:
        if not _is_empty_response_error(exc):
            raise
        print(f"⚠️ Primary model returned empty response, retrying with {FALLBACK_MODEL}…")
        fallback_agent = build_agent(*args, **kwargs, model_name=FALLBACK_MODEL)
        if deps is not None:
            return await fallback_agent.run(prompt, deps=deps)
        return await fallback_agent.run(prompt)


def _format_simple_response(query: str, plan: QueryPlan, execution: ExecutionResult) -> str | None:
    """Generate a deterministic response for simple queries without calling the LLM.

    Returns None if the query is complex enough to warrant the responder agent.
    Handles:
    - Single retrieve_numbers (1 item): "Revenue in 2022 was $1,234,567"
    - Simple named operations with explanation: "The sum is $2,000"
    """
    step_results = execution.step_results or {}
    final = execution.final_answer
    explanation = execution.explanation or ""

    # Case 1: retrieve_numbers with 1-2 items
    if plan.task_type == "retrieve_numbers" and plan.items:
        if len(plan.items) <= 2:
            parts = []
            for item in plan.items:
                fields = [f.strip() for f in item.split(",")]
                if len(fields) == 2:
                    field_name, year = fields
                    val = final if len(plan.items) == 1 else step_results.get(f"item_{fields[0]}_{fields[1]}", final)
                    parts.append(f"{field_name} in {year}: {val}")
                elif len(fields) == 3:
                    sheet_name, field_name, year = fields
                    parts.append(f"{field_name} in {year} ({sheet_name}): {final}")
            if parts:
                return "  |  ".join(parts)

    # Case 2: single-step plan with a clear explanation
    if plan.plan and len(plan.plan) == 1 and explanation:
        step_name = list(plan.plan.keys())[0]
        step = plan.plan[step_name]
        val = step_results.get(step_name, final)
        if step.action == "retrieve":
            return f"{explanation}: {val}"
        # Simple named ops with explanation
        if val is not None and explanation:
            return f"{explanation}: {val}"

    return None


# ============================================================================
# Optimization 2: Pre-populate retrievals in pure Python (no LLM)
# ============================================================================

def _looks_like_year(s: str) -> bool:
    """Return True if ``s`` parses as a 4-digit year (e.g. "2022", "2022.0")."""
    if not s:
        return False
    s = s.strip()
    if len(s) == 4 and s.isdigit() and 1900 <= int(s) <= 2100:
        return True
    if s.endswith(".0") and s[:-2].isdigit() and 1900 <= int(s[:-2]) <= 2100:
        return True
    return False


def _prepopulate_retrievals(plan: QueryPlan, deps: PipelineDeps) -> dict[str, Any]:
    """Execute every retrieve / retrieve_batch step in pure Python (no LLM).

    Optimization 2: collapses N sequential LLM round-trips into a single
    Python pass before the executor runs. The executor then only handles
    computation + friendly-response generation.

    The returned dict maps step name → retrieved value (a scalar string from
    ``retrieve`` or a parsed dict from ``retrieve_batch``). Per-step failures
    are captured as ``"ERROR: ..."`` strings so downstream code can decide.
    """
    from types import SimpleNamespace

    pre_populated: dict[str, Any] = {}
    if not plan.plan:
        return pre_populated

    # ``retrieve`` and ``retrieve_batch`` only touch ``ctx.deps`` — a
    # SimpleNamespace is sufficient.
    ctx = SimpleNamespace(deps=deps)

    for name, step in plan.plan.items():
        args = step.args or []
        try:
            if step.action == "retrieve":
                if len(args) == 2:
                    field, year = args
                    pre_populated[name] = retrieve(ctx, field, year)
                elif len(args) == 3:
                    sheet, field, year = args
                    pre_populated[name] = retrieve(ctx, field, year, sheet)
                else:
                    pre_populated[name] = f"ERROR: retrieve expects 2 or 3 args, got {len(args)}"
            elif step.action == "retrieve_batch":
                # Cross-sheet: ["Field", "Year1", "Year2", ...] → args[1] is a year
                # Specific sheet: ["Sheet", "Field", "Year1", ...] → args[1] is the field
                if len(args) < 2:
                    pre_populated[name] = "ERROR: retrieve_batch needs at least 2 args"
                    continue
                if _looks_like_year(args[1]):
                    field = args[0]
                    years = args[1:]
                    raw = retrieve_batch(ctx, field, years, sheet="")
                else:
                    sheet = args[0]
                    field = args[1]
                    years = args[2:]
                    raw = retrieve_batch(ctx, field, years, sheet=sheet)
                try:
                    pre_populated[name] = json.loads(raw)
                except (json.JSONDecodeError, TypeError):
                    pre_populated[name] = raw
            else:
                # Named ops / compute can't be pre-populated — leave for executor.
                continue
        except Exception as e:
            print(f"⚠️ Pre-populate failed for {name}: {e}")
            pre_populated[name] = f"ERROR: {type(e).__name__}: {e}"

    return pre_populated


def _format_pre_populated_for_prompt(pre_populated: dict[str, Any]) -> str:
    """Render pre-populated values as a human-readable block for the executor.

    Format:
        Pre-computed values (use these directly, do NOT call retrieve):

        step1: 1500.0
        step2: 1200.0
        step3: {"2018": 1500.0, "2019": 1200.0}
    """
    if not pre_populated:
        return ""
    lines = [
        "Pre-computed values (use these directly — do NOT call retrieve or "
        "retrieve_batch again):"
    ]
    for name, value in pre_populated.items():
        lines.append(f"  {name}: {value}")
    return "\n".join(lines)


def _plan_is_pure_retrieve(plan: QueryPlan) -> bool:
    """True iff every step is a retrieve/retrieve_batch (no compute, no named ops)."""
    if not plan.plan:
        return False
    return all(
        step.action in {"retrieve", "retrieve_batch"}
        for step in plan.plan.values()
    )


# ============================================================================
# Public Pipeline API
# ============================================================================

def build_query_pipeline(
    llm_client: Any | None,
    sheets: dict[str, pd.DataFrame],
    sheet_metas: list[SheetMeta],
    classification_template: PromptTemplate,
    user_id: str = "anonymous",
    on_event: Callable[[str, dict[str, Any]], None] | None = None,
) -> Any:
    """
    Build a Pydantic AI agent pipeline for querying financial data across multiple sheets.

    Returns a callable that accepts a query string and returns the pipeline result.
    The llm_client argument is kept for backward compatibility but ignored;
    agents create their own OpenRouter model internally.
    """
    all_fields = sorted(set(f for meta in sheet_metas for f in meta.fields))
    all_years = sorted(set(y for meta in sheet_metas for y in meta.years))

    def _emit(event_type: str, data: dict[str, Any]) -> None:
        if on_event:
            try:
                on_event(event_type, data)
            except Exception:
                pass

    async def run_pipeline(query: str) -> dict:
        # Optimization 6: per-stage timing dict returned alongside the answer.
        timings: dict[str, float] = {}

        # Step 1: Plan
        _emit("status", {"message": "Analyzing your question…"})
        with timed("planner", timings):
            plan_result = await _run_with_fallback(
                build_planner_agent, query, sheets, sheet_metas
            )
        plan: QueryPlan = plan_result.data
        print("Plan:", json.dumps(plan.model_dump(), indent=2))

        # Emit classified intent + plan
        _emit("plan", {
            "task_type": plan.task_type,
            "plan": plan.model_dump().get("plan"),
            "items": plan.items,
            "description": plan.description,
        })

        # Step 2: Execute
        deps = PipelineDeps(
            sheets=sheets,
            sheet_metas=sheet_metas,
            original_query=query,
            available_fields=all_fields,
            available_years=all_years,
            user_id=user_id,
        )

        # ------------------------------------------------------------------
        # Optimization 2: pre-populate retrieve / retrieve_batch steps in pure
        # Python. The executor then only has to handle compute / friendly
        # response, which collapses the LLM round-trip count.
        # ------------------------------------------------------------------
        pre_populated: dict[str, Any] = {}
        if plan.plan:
            _emit("status", {"message": "Retrieving data from sheets…"})
            with timed("pre_populate", timings):
                pre_populated = _prepopulate_retrievals(plan, deps)
            if pre_populated:
                print(f"Pre-populated {len(pre_populated)} values: {pre_populated}")
                _emit("pre_populated", {"values": pre_populated})

        # ------------------------------------------------------------------
        # Short-circuit: if every step is a retrieve/retrieve_batch, we don't
        # need the executor at all. Build the ExecutionResult directly.
        # ------------------------------------------------------------------
        if plan.plan and _plan_is_pure_retrieve(plan):
            step_results: dict[str, Any] = {}
            final_answers: list[Any] = []
            for name, step in plan.plan.items():
                val = pre_populated.get(name)
                step_results[name] = val
                if not str(val).startswith("ERROR"):
                    final_answers.append(val)
            # Single value → scalar; multiple → list.
            final_answer: Any = (
                final_answers[0] if len(final_answers) == 1 else final_answers
            )
            execution = ExecutionResult(
                step_results=step_results,
                final_answer=final_answer,
                explanation=(
                    f"Retrieved {len(final_answers)} value(s) directly from the "
                    "DataFrame (no executor LLM call required)."
                ),
                friendly_response="",  # filled in by _format_simple_response
            )
            _emit("status", {"message": "All values retrieved — preparing answer…"})
            print("Skipped executor — pure retrieve plan.")
            try:
                from result_cache import cache_step_results
                cache_step_results(user_id, plan, execution)
            except Exception as e:
                print(f"⚠️ Post-execution caching failed: {e}")
            friendly = inject_disclaimer(_format_simple_response(query, plan, execution) or "")
            if friendly:
                print(f"Response: {friendly[:100]}...")
            _emit("friendly", {"response": friendly})
            total = sum(timings.values())
            print(f"Pipeline total: {total:.2f}s | {timings}")
            _emit("done", {"timings": timings, "total": total})
            return {
                "answer": execution.model_dump(),
                "friendly_response": friendly,
                "timings": timings,
            }

        _emit("status", {"message": "Running calculations…"})

        # Build execution prompt from the plan
        if plan.task_type == "retrieve_numbers" and plan.items:
            exec_prompt = (
                f"Retrieve the following values and return them as the final answer: {plan.items}"
            )
        elif plan.plan:
            retrieve_steps = []
            named_steps = []
            compute_desc = ""
            # Build a step-to-field-name mapping so the executor knows which
            # field each step refers to (for use in friendly_response).
            step_field_map: list[str] = []
            for name, step in plan.plan.items():
                if step.action in {"retrieve", "retrieve_batch"}:
                    # Extract field name from args for context
                    if step.action == "retrieve_batch":
                        if _looks_like_year(step.args[1] if len(step.args) > 1 else ""):
                            field_name = step.args[0] if step.args else ""
                        else:
                            field_name = step.args[1] if len(step.args) > 1 else ""
                    else:
                        field_name = step.args[0] if step.args else ""
                    step_field_map.append(f"  {name} → field: {field_name}")
                    # If we already pre-populated this step, tell the executor
                    # to use the literal value instead of re-fetching.
                    if name in pre_populated:
                        retrieve_steps.append(
                            f"  {name} (field: {field_name}): ALREADY DONE — value is {pre_populated[name]}"
                        )
                    else:
                        verb = "retrieve_batch" if step.action == "retrieve_batch" else "retrieve"
                        retrieve_steps.append(f"  {name} (field: {field_name}): {verb}({step.args})")
                elif step.action == "compute":
                    compute_desc = step.args[0] if step.args else ""
                elif step.action in NAMED_OPERATIONS:
                    named_steps.append(f"  {name}: {step.action}({step.args})")
            steps_desc = "\n".join(retrieve_steps)
            named_desc = "\n".join(named_steps)
            pre_populated_block = _format_pre_populated_for_prompt(pre_populated)
            parts = []
            if pre_populated_block:
                parts.append(pre_populated_block)
            if retrieve_steps:
                parts.append(f"Retrieve these values:\n{steps_desc}")
            if named_steps:
                parts.append(f"Apply these named operations:\n{named_desc}")
            if compute_desc:
                parts.append(f"Then use execute_python_code to calculate: {compute_desc}")
            # Include step-to-field mapping so executor can name fields in friendly_response
            if step_field_map:
                parts.append(
                    "Step-to-field mapping (use these field names in your friendly_response):\n"
                    + "\n".join(step_field_map)
                )
            parts.append(f"User query: {query}")
            exec_prompt = "\n\n".join(parts)
        else:
            exec_prompt = query

        with timed("executor", timings):
            exec_result = await _run_with_fallback(
                build_executor_agent, exec_prompt, sheets, sheet_metas, deps=deps
            )
        execution: ExecutionResult = exec_result.data
        print("✅ Execution:", json.dumps(execution.model_dump(), indent=2))
        _emit("execution", {"step_results": execution.step_results, "final_answer": execution.final_answer, "explanation": execution.explanation})

        # Layer 3: Post-execution structured key derivation
        try:
            from result_cache import cache_step_results
            cache_step_results(user_id, plan, execution)
        except Exception as e:
            print(f"⚠️ Post-execution caching failed: {e}")

        # Step 3: Use executor's friendly_response (merged responder)
        friendly = inject_disclaimer(
            execution.friendly_response or _format_simple_response(query, plan, execution) or ""
        )
        if friendly:
            print(f"Response: {friendly[:100]}...")
        else:
            print("⚠️ No friendly response generated")
        _emit("friendly", {"response": friendly})

        total = sum(timings.values())
        print(f"Pipeline total: {total:.2f}s | {timings}")
        _emit("done", {"timings": timings, "total": total})
        return {
            "answer": execution.model_dump(),
            "friendly_response": friendly,
            "timings": timings,
        }

    return run_pipeline


async def generate_user_friendly_response(
    llm_client: Any | None, original_query: str, json_result: Any
) -> str:
    """
    Generate a user-friendly response from the JSON result.
    llm_client is kept for backward compatibility but ignored.
    """
    responder = build_responder_agent()
    prompt = f"""User's Question: {original_query}

    Calculated Results:
    {json.dumps(json_result, indent=2)}

    Provide a clear, natural language response."""
    result = await _run_with_fallback(build_responder_agent, prompt)
    return inject_disclaimer(result.data)


# ============================================================================
# Legacy helper functions (preserved for backward compatibility)
# ============================================================================

def executing_plan_from_json(df: pd.DataFrame, json_str: str) -> dict[str, Any]:
    """
    Legacy deterministic plan executor. Kept for backward compatibility.
    """
    try:
        parsed = json.loads(json_str)
        print("Parsed JSON:", parsed)

        if "plan" in parsed:
            plan = parsed["plan"]
        elif "items" in parsed:
            plan = {
                f"step{i + 1}": {"action": "retrieve", "args": item.split(",")}
                for i, item in enumerate(parsed["items"])
            }
        else:
            raise ValueError("Invalid JSON format - missing 'plan' or 'items'")

        context: dict[str, Any] = {}
        computed_values: dict[str, Any] = {}

        for step_name, instruction in plan.items():
            print(f"Processing step {step_name}: {instruction}")

            if isinstance(instruction, str):
                instruction = instruction.strip()
                if instruction.lower().startswith("retrieve"):
                    args_part = instruction[8:].strip().strip("[]'\"")
                    parts = [p.strip().strip("'\"") for p in args_part.split(",")]
                    if len(parts) >= 2:
                        col, year = parts[0], parts[1]
                        values = _legacy_retrieving(df, [col, year])
                        context[step_name] = values[0] if values else None
                        computed_values[step_name] = context[step_name]
                continue

            if isinstance(instruction, dict):
                action = instruction.get("action", "").lower()
                args = instruction.get("args", [])

                normalized_args = []
                for arg in args:
                    if isinstance(arg, str) and "," in arg:
                        normalized_args.extend([x.strip() for x in arg.split(",")])
                    else:
                        normalized_args.append(arg.strip() if isinstance(arg, str) else arg)

                if action == "retrieve":
                    if len(normalized_args) >= 2:
                        col, year = normalized_args[0], normalized_args[1]
                        values = _legacy_retrieving(df, [col, year])
                        context[step_name] = values[0] if values else None
                        computed_values[step_name] = context[step_name]
                    else:
                        context[step_name] = None

                elif action in NAMED_OPERATIONS:
                    func = NAMED_OPERATIONS[action]
                    resolved_vals = []
                    for arg in args:
                        val = _resolve_arg(arg, computed_values)
                        if val is None:
                            context[step_name] = None
                            break
                        resolved_vals.append(val)
                    else:
                        try:
                            context[step_name] = func(*resolved_vals)
                            computed_values[step_name] = context[step_name]
                        except Exception as e:
                            print(f"⚠️ Error in {action}: {e}")
                            context[step_name] = None
                else:
                    context[step_name] = None
                continue

            context[step_name] = None

        print("✅ Final context:", context)
        return context

    except Exception as e:
        print(f"❌ Error in execution: {str(e)}")
        raise


def _legacy_retrieving(df: pd.DataFrame, items: list[str]) -> list[float | None]:
    print(f"Attempting to retrieve: {items}")
    if len(items) == 2:
        col, year = items[0].strip(), items[1].strip()
        print(
            f"Looking for: '{col}' in index ({col in df.index}), "
            f"'{year}' in columns ({year in df.columns})"
        )
        if col in df.index and year in df.columns:
            val = df.loc[col, year]
            print(f"✅ Found value: {val}")
            return [float(val)]
    print("❌ Value not found")
    return [None]


def _resolve_arg(arg: Any, computed_values: dict[str, Any]) -> float | None:
    if isinstance(arg, str) and arg.startswith("step"):
        return computed_values.get(arg.strip())
    if isinstance(arg, (int, float)):
        return float(arg)
    try:
        return float(arg)
    except (ValueError, TypeError):
        return None