from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from typing import Any, Literal

import pandas as pd
import pydantic_monty
from pydantic import BaseModel, Field
from pydantic_ai import Agent, RunContext, Tool
from pydantic_ai.models.openai import OpenAIModel
from pydantic_ai.tools import ToolDefinition

from llama_index.core.prompts import PromptTemplate


# ============================================================================
# Structured Output Models
# ============================================================================

class PlanStep(BaseModel):
    """A single step in the execution plan."""
    action: Literal[
        "retrieve", "add", "subtract", "multiply", "divide", "return_percentage"
    ] = Field(description="The action to perform in this step.")
    args: list[str] = Field(
        description=(
            "Arguments for the action. For 'retrieve', use ['FieldName', 'Year']. "
            "For calculations, use ['stepX', 'stepY'] or literal numbers."
        )
    )


class QueryPlan(BaseModel):
    """Structured plan generated by the planner agent."""
    task_type: Literal[
        "retrieve_numbers", "perform_calculations", "give_advice", "other"
    ] = Field(description="The type of task the user is asking for.")
    plan: dict[str, PlanStep] | None = Field(
        default=None,
        description="Numbered steps for 'perform_calculations' tasks.",
    )
    items: list[str] | None = Field(
        default=None,
        description="List of 'FieldName, Year' strings for 'retrieve_numbers' tasks.",
    )
    description: str | None = Field(
        default=None,
        description="Description of advice needed for 'give_advice' tasks.",
    )


class ExecutionResult(BaseModel):
    """Result of executing a query plan."""
    step_results: dict[str, Any] = Field(
        default_factory=dict,
        description="Results from each executed step.",
    )
    final_answer: Any = Field(
        description="The final computed or retrieved answer.",
    )
    explanation: str = Field(
        default="",
        description="Brief explanation of how the answer was derived.",
    )


class FriendlyResponse(BaseModel):
    """User-friendly natural language response."""
    response: str = Field(description="The conversational response to the user.")


# ============================================================================
# Dependencies
# ============================================================================

@dataclass
class PipelineDeps:
    """Dependencies passed through RunContext to tools and agents."""
    df: pd.DataFrame
    original_query: str
    computed_values: dict[str, Any] = field(default_factory=dict)
    available_fields: list[str] = field(default_factory=list)
    available_years: list[str] = field(default_factory=list)


# ============================================================================
# Model Factory
# ============================================================================

def build_openrouter_model() -> OpenAIModel:
    """Create an OpenAIModel configured for OpenRouter."""
    return OpenAIModel(
        model_name="deepseek/deepseek-v4-flash",
        base_url=os.environ.get("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1"),
        api_key=os.environ.get("OPENROUTER_API_KEY"),
    )


# ============================================================================
# Tools
# ============================================================================

def retrieve(ctx: RunContext[PipelineDeps], field: str, year: str) -> str:
    """Retrieve a numeric value from the financial DataFrame."""
    df = ctx.deps.df
    if field in df.index and year in df.columns:
        val = df.loc[field, year]
        return str(float(val))
    return f"ERROR: '{field}' or '{year}' not found in data."


def extract_val(ctx: RunContext[PipelineDeps], field: str, year: str) -> str:
    """Extract a single value from the DataFrame by field and year."""
    return retrieve(ctx, field, year)


def add_tool(ctx: RunContext[PipelineDeps], a: float, b: float) -> float:
    """Add two numbers together."""
    return a + b


def multiply_tool(ctx: RunContext[PipelineDeps], a: float, b: float) -> float:
    """Multiply two numbers."""
    return a * b


def subtract_tool(ctx: RunContext[PipelineDeps], a: float, b: float) -> float:
    """Subtract the second number from the first."""
    return a - b


def divide_tool(ctx: RunContext[PipelineDeps], a: float, b: float) -> str:
    """Divide the first number by the second. Returns error string on division by zero."""
    if b == 0 or b is None:
        return "ERROR: Division by zero"
    return str(a / b)


def return_percentage_tool(ctx: RunContext[PipelineDeps], a: float, b: float) -> str:
    """Calculate (a / b) * 100. Returns error string on division by zero."""
    if b == 0 or b is None:
        return "ERROR: Division by zero"
    return str((a / b) * 100)


def execute_python_code(ctx: RunContext[PipelineDeps], code: str) -> str:
    """
    Execute Python code in a secure sandbox using pydantic-monty.
    
    This tool allows the agent to perform mathematical operations or custom calculations
    that are not covered by the basic toolkit. The sandbox provides a secure environment
    for executing Python code written by the LLM.
    
    The code should use a `return` statement to return the result.
    
    Example usage:
        code = "return 10 + 20"
        code = "return (100 * 1.05) ** 3"
    
    Available in the sandbox:
    - Basic Python syntax and operators
    - Common math functions (via monty's built-in math module)
    - Computed values from previous steps (via context)
    """
    import asyncio
    import io
    import sys
    
    try:
        # Modify code to ensure it has a return statement if it doesn't
        # If code assigns to 'result' or 'result_', add a return statement
        code_stripped = code.strip()
        if not code_stripped.startswith("return"):
            # Check if it assigns to result variable
            if "result " in code or "result=" in code:
                # Extract the last line that assigns to result
                lines = code.split("\n")
                for line in reversed(lines):
                    if "result" in line and ("=" in line or "result" in line):
                        # Convert assignment to return
                        if "=" in line:
                            expr = line.split("=", 1)[1].strip()
                            code = f"return {expr}"
                        else:
                            code = f"return {line}"
                        break
        
        # Create type definitions for the sandbox
        type_defs = """
import math
from typing import Any

# Computed values from the pipeline will be injected
"""
        
        # Add computed values to type definitions
        for key, value in ctx.deps.computed_values.items():
            if isinstance(value, (int, float)):
                type_defs += f"{key}: float = 0.0\n"
            else:
                type_defs += f"{key}: Any = None\n"
        
        # Prepare external functions that the sandbox can call
        external_functions = {}
        
        # Create the Monty instance
        m = pydantic_monty.Monty(
            code,
            inputs=[],
            script_name="sandbox.py",
            type_check=False,
            type_check_stubs=type_defs,
        )
        
        # Capture stdout
        old_stdout = sys.stdout
        stdout_capture = io.StringIO()
        
        try:
            sys.stdout = stdout_capture
            
            # Run the code asynchronously
            async def run_monty():
                return await m.run_async(
                    inputs={},
                    external_functions=external_functions,
                )
            
            output = asyncio.run(run_monty())
            
            # Get captured stdout
            stdout_output = stdout_capture.getvalue()
            
            # Return output from return statement or stdout
            if output is not None:
                return str(output)
            elif stdout_output:
                return stdout_output.strip()
            else:
                return "Code executed successfully (no output)"
                
        finally:
            sys.stdout = old_stdout
        
    except Exception as e:
        return f"ERROR: {type(e).__name__}: {str(e)}"


# ============================================================================
# Tool Prepare Functions (dynamic schema customization)
# ============================================================================

async def _prepare_retrieve_tool(
    ctx: RunContext[PipelineDeps], tool_def: ToolDefinition
) -> ToolDefinition | None:
    """Inject available fields/years into the retrieve tool schema."""
    fields = ctx.deps.available_fields
    years = ctx.deps.available_years
    tool_def.parameters_json_schema["properties"]["field"]["description"] = (
        f"Field name from available fields: {', '.join(fields)}"
    )
    tool_def.parameters_json_schema["properties"]["year"]["description"] = (
        f"Year from available years: {', '.join(years)}"
    )
    return tool_def


async def _prepare_extract_val_tool(
    ctx: RunContext[PipelineDeps], tool_def: ToolDefinition
) -> ToolDefinition | None:
    """Inject available fields/years into the extract_val tool schema."""
    return await _prepare_retrieve_tool(ctx, tool_def)


# ============================================================================
# Agent Builders
# ============================================================================

def build_planner_agent(df: pd.DataFrame) -> Agent[None, QueryPlan]:
    """Agent that generates a structured QueryPlan from a user question."""
    model = build_openrouter_model()
    fields = [str(f) for f in df.index]
    years = [str(y) for y in df.columns]

    instructions = f"""You are a financial data analysis planner.

Available fields: {', '.join(fields)}
Available years: {', '.join(years)}

Task types:
- retrieve_numbers: Simple lookups (e.g., "What was revenue in 2022?")
- perform_calculations: Math operations (e.g., "What's the profit margin?")
- give_advice: Recommendations or analysis
- other: Everything else

For retrieve_numbers: return items like ["Revenue, 2022"]
For perform_calculations: return a plan with numbered steps:
  - retrieve ["FieldName", "Year"]
  - add / subtract / multiply / divide / return_percentage ["stepX", "stepY"]
  
Always use exact field names and years from the available lists.
"""

    return Agent(
        model,
        result_type=QueryPlan,
        system_prompt=instructions,
        model_settings={"temperature": 0.1},
    )


def build_executor_agent(df: pd.DataFrame) -> Agent[PipelineDeps, ExecutionResult]:
    """Agent that executes a plan using tools, with structured output."""
    model = build_openrouter_model()

    retrieve_t = Tool(retrieve, prepare=_prepare_retrieve_tool)
    extract_t = Tool(extract_val, prepare=_prepare_extract_val_tool)

    system_prompt = """You are a financial data execution engine.

You have tools to retrieve values from a DataFrame and perform arithmetic.
Execute the user's query step by step:
1. Call retrieve/extract_val to get needed values
2. Call arithmetic tools (add, subtract, multiply, divide, return_percentage) to compute results
3. For complex calculations not covered by basic tools, use execute_python_code to run Python code in a secure sandbox
4. Return the final answer as structured data

If a step fails, note it and continue with what you can.
"""

    return Agent(
        model,
        deps_type=PipelineDeps,
        result_type=ExecutionResult,
        system_prompt=system_prompt,
        tools=[
            retrieve_t,
            extract_t,
            add_tool,
            multiply_tool,
            subtract_tool,
            divide_tool,
            return_percentage_tool,
            execute_python_code,
        ],
        model_settings={"temperature": 0.1},
    )


def build_responder_agent() -> Agent[None, str]:
    """Agent that generates a friendly natural language response."""
    model = build_openrouter_model()

    return Agent(
        model,
        result_type=str,
        system_prompt="""You are a helpful financial assistant.

Given a user's question and the calculated results, provide a clear, conversational
response that directly answers the question. Include specific numerical values
with proper formatting (currency, percentages). Briefly explain how the answer
was derived. Use a friendly, professional tone.
""",
        model_settings={"temperature": 0.3},
    )


# ============================================================================
# Public Pipeline API
# ============================================================================

def build_query_pipeline(
    llm_client: Any | None, df: pd.DataFrame, classification_template: PromptTemplate
) -> Any:
    """
    Build a Pydantic AI agent pipeline for querying financial data.

    Returns a callable that accepts a query string and returns the pipeline result.
    The llm_client argument is kept for backward compatibility but ignored;
    agents create their own OpenRouter model internally.
    """
    fields = [str(f) for f in df.index]
    years = [str(y) for y in df.columns]

    def run_pipeline(query: str) -> dict:
        # Step 1: Plan
        planner = build_planner_agent(df)
        plan_result = planner.run_sync(query)
        plan: QueryPlan = plan_result.data
        print("📋 Plan:", json.dumps(plan.model_dump(), indent=2))

        # Step 2: Execute
        deps = PipelineDeps(
            df=df,
            original_query=query,
            available_fields=fields,
            available_years=years,
        )
        executor = build_executor_agent(df)

        # Build execution prompt from the plan
        if plan.task_type == "retrieve_numbers" and plan.items:
            exec_prompt = (
                f"Retrieve the following values and return them as the final answer: {plan.items}"
            )
        elif plan.plan:
            steps_desc = "\n".join(
                f"{name}: {step.action}({step.args})"
                for name, step in plan.plan.items()
            )
            exec_prompt = (
                f"Execute this plan step by step:\n{steps_desc}\n\n"
                f"User query: {query}"
            )
        else:
            exec_prompt = query

        exec_result = executor.run_sync(exec_prompt, deps=deps)
        execution: ExecutionResult = exec_result.data
        print("✅ Execution:", json.dumps(execution.model_dump(), indent=2))

        # Step 3: Respond
        responder = build_responder_agent()
        resp_prompt = f"""User's Question: {query}

Execution Results:
{json.dumps(execution.model_dump(), indent=2)}

Provide a clear, natural language response."""
        resp_result = responder.run_sync(resp_prompt)
        friendly: str = resp_result.data
        print(f"📝 Response: {friendly[:100]}...")

        return {
            "answer": execution.model_dump(),
            "friendly_response": friendly,
        }

    return run_pipeline


def generate_user_friendly_response(
    llm_client: Any | None, original_query: str, json_result: Any
) -> str:
    """
    Generate a user-friendly response from the JSON result.
    llm_client is kept for backward compatibility but ignored.
    """
    responder = build_responder_agent()
    prompt = f"""User's Question: {original_query}

Calculated Results:
{json.dumps(json_result, indent=2)}

Provide a clear, natural language response."""
    result = responder.run_sync(prompt)
    return result.data


# ============================================================================
# Legacy helper functions (preserved for backward compatibility)
# ============================================================================

def executing_plan_from_json(df: pd.DataFrame, json_str: str) -> dict[str, Any]:
    """
    Legacy deterministic plan executor. Kept for backward compatibility.
    """
    try:
        parsed = json.loads(json_str)
        print("🔨 Parsed JSON:", parsed)

        if "plan" in parsed:
            plan = parsed["plan"]
        elif "items" in parsed:
            plan = {
                f"step{i + 1}": {"action": "retrieve", "args": item.split(",")}
                for i, item in enumerate(parsed["items"])
            }
        else:
            raise ValueError("Invalid JSON format - missing 'plan' or 'items'")

        context: dict[str, Any] = {}
        computed_values: dict[str, Any] = {}

        for step_name, instruction in plan.items():
            print(f"🔧 Processing step {step_name}: {instruction}")

            if isinstance(instruction, str):
                instruction = instruction.strip()
                if instruction.lower().startswith("retrieve"):
                    args_part = instruction[8:].strip().strip("[]'\"")
                    parts = [p.strip().strip("'\"") for p in args_part.split(",")]
                    if len(parts) >= 2:
                        col, year = parts[0], parts[1]
                        values = _legacy_retrieving(df, [col, year])
                        context[step_name] = values[0] if values else None
                        computed_values[step_name] = context[step_name]
                continue

            if isinstance(instruction, dict):
                action = instruction.get("action", "").lower()
                args = instruction.get("args", [])

                normalized_args = []
                for arg in args:
                    if isinstance(arg, str) and "," in arg:
                        normalized_args.extend([x.strip() for x in arg.split(",")])
                    else:
                        normalized_args.append(arg.strip() if isinstance(arg, str) else arg)

                if action == "retrieve":
                    if len(normalized_args) >= 2:
                        col, year = normalized_args[0], normalized_args[1]
                        values = _legacy_retrieving(df, [col, year])
                        context[step_name] = values[0] if values else None
                        computed_values[step_name] = context[step_name]
                    else:
                        context[step_name] = None

                elif action in ("add", "subtract", "multiply", "divide", "return_percentage"):
                    if len(args) == 2:
                        arg1, arg2 = args
                        val1 = _resolve_arg(arg1, computed_values)
                        val2 = _resolve_arg(arg2, computed_values)

                        if val1 is not None and val2 is not None:
                            if action == "add":
                                context[step_name] = val1 + val2
                            elif action == "subtract":
                                context[step_name] = val1 - val2
                            elif action == "multiply":
                                context[step_name] = val1 * val2
                            elif action == "divide":
                                context[step_name] = (
                                    val1 / val2 if val2 != 0 else None
                                )
                            elif action == "return_percentage":
                                context[step_name] = (
                                    (val1 / val2) * 100 if val2 != 0 else None
                                )
                            computed_values[step_name] = context[step_name]
                        else:
                            context[step_name] = None
                    else:
                        context[step_name] = None
                else:
                    context[step_name] = None
                continue

            context[step_name] = None

        print("✅ Final context:", context)
        return context

    except Exception as e:
        print(f"❌ Error in execution: {str(e)}")
        raise


def _legacy_retrieving(df: pd.DataFrame, items: list[str]) -> list[float | None]:
    print(f"🔍 Attempting to retrieve: {items}")
    if len(items) == 2:
        col, year = items[0].strip(), items[1].strip()
        print(
            f"🔍 Looking for: '{col}' in index ({col in df.index}), "
            f"'{year}' in columns ({year in df.columns})"
        )
        if col in df.index and year in df.columns:
            val = df.loc[col, year]
            print(f"✅ Found value: {val}")
            return [float(val)]
    print("❌ Value not found")
    return [None]


def _resolve_arg(arg: Any, computed_values: dict[str, Any]) -> float | None:
    if isinstance(arg, str) and arg.startswith("step"):
        return computed_values.get(arg.strip())
    if isinstance(arg, (int, float)):
        return float(arg)
    try:
        return float(arg)
    except (ValueError, TypeError):
        return None